Адаптивная сетка каталога
htmlacademy-adaptive/1481739-pink-21 pull request #10
Opened 2020-12-01 19:57 UTC by olga2102

2020-12-01 20:13 UTC, Shramkoweb requested changes

2020-12-01 20:13 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="main-nav__link" href="catalog.html">
В каталоге нет ссылки на него же.
<a class="main-nav__link" >

2020-12-01 20:13 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="main-nav__link">
Мы же сейчас в каталоге, а ты убрала форму?
Что-то тут не так..

2020-12-01 20:13 UTC, Shramkoweb commented on source/catalog.html
> +      <p class="photos__intro container">
Это точно не контейнер

2020-12-01 20:13 UTC, Shramkoweb commented on source/catalog.html
> +      <p class="photo-editor__slogan container">Затмите их всех!<br> Выкладывайте все, что накопилось в телефоне!
Не контейнер

2020-12-01 20:13 UTC, Shramkoweb commented on source/catalog.html
> +        <div class="photo-editor__wrapper container">
Не контейнер.

Контейнер - это не то, где тебе просто нужно его стили. Это блок который оборачивает целый раздел. У тебя просто тут стоит что-то замиксовать

2020-12-01 20:13 UTC, Shramkoweb commented on source/sass/blocks/catalog/photo-editor.scss
> +    width: 940px;
width: 100% не?

2020-12-01 20:13 UTC, Shramkoweb commented on source/sass/blocks/catalog/photos.scss
> +.photos__main__link {
Элемент эелемента?

2020-12-01 20:23 UTC, olga2102 commented on source/catalog.html
> +            <a class="main-nav__link">
все напутала)

2020-12-01 20:23 UTC, olga2102 commented on source/catalog.html
> +      <p class="photos__intro container">
я могу же в див контейнер обернуть?

2020-12-01 20:28 UTC, olga2102 commented on source/sass/blocks/catalog/photo-editor.scss
> +    width: 940px;
так если 100, то он будет же 960, а не 940?

2020-12-01 20:30 UTC, olga2102 commented on source/sass/blocks/catalog/photos.scss
> +.photos__main__link {
ой исправила

2020-12-01 20:33 UTC, olga2102 commented on source/catalog.html
> +        <div class="photo-editor__wrapper container">
а вот тут не поняла. почему это не контейнер?

2020-12-02 19:06 UTC, Shramkoweb commented on source/sass/blocks/catalog/photo-editor.scss
> +    width: 940px;
Для этого гдето снаружи должен быть контейнер

2020-12-02 19:09 UTC, Shramkoweb approved these changes

2020-12-02 19:09 UTC, Shramkoweb commented on source/catalog.html
> +        <div class="photo-editor__wrapper container">
Если обернуть то норм

2020-12-02 19:09 UTC, merged