Поправила сетку для главной, добавила контейнер
htmlacademy-adaptive/1481739-pink-21 pull request #11
Opened 2020-12-02 21:27 UTC by olga2102

2020-12-05 21:49 UTC, olga2102 reviewed
Стайлгайд пока не делала и пп шапки. хочу сделать, когда задание по свг будет.

2020-12-05 21:49 UTC, olga2102 commented on source/index.html
> +            Британские ученые провели исследование<br class="research__break"> и доказали, что положительный эффект<br class="research__break"> от использования приложения
по пп не смогла поставить блок в десктопе. будешь проверять, напиши мне, плиз, я пришлю скрин. щас поздно отправлять.

2020-12-06 11:23 UTC, Shramkoweb requested changes
![image](https://user-images.githubusercontent.com/42001531/101278718-1dec2680-37c6-11eb-8739-eebdc203eb14.png)

![image](https://user-images.githubusercontent.com/42001531/101278726-32c8ba00-37c6-11eb-9632-d960517ac5fb.png)


Насколько я помню, логотип адаптивный. У тебя не увидел адаптивности, или это в след задании?

2020-12-06 11:23 UTC, Shramkoweb commented on source/index.html
> +      <div class="container">
Нельзя ли container повесить на section выше?

2020-12-06 11:23 UTC, Shramkoweb commented on source/index.html
> +      <div class="container slider">
Аналогично, нельзя ли его вынести выше на section?

2020-12-06 11:23 UTC, Shramkoweb commented on source/index.html
> +      <div class="container">
Аналогично, контейнер выше на section ?

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/advantages-item.scss
> +      transform: translate(-50%, -50%);
Код дублируешь. Может вынести все стили для самой иконки в `advantages-item::before` а потом по модификаторам, менять просто фон?

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/advantages-item.scss
> +      background-repeat: no-repeat;
Аналогично

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/contacts.scss
> +.contacts__wrapper-tel,
Может им просто дать один класс?

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/reviews.scss
> +.reviews__next {
Вынести в общий класс. review__control

По модификатору меняй иконки и позиции если нужно

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/reviews.scss
> +.reviews__prev {
А Вот это уже модификаторы должны быть

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs-data.scss
> +.tariffs-data-header {
Это какой-то уже другой бем блок?

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs-data.scss
> +.tariffs-data--hit {
Модификатор через амперсанд

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs-data.scss
> +.tariffs-data--empty {
Черезх амперсанд

2020-12-06 11:23 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs.scss
> +      line-height: 30px;
Три раза продублировала. Что-то надо сделать.
Или общий класс, или через запятую селекторы

2020-12-06 11:47 UTC, olga2102 commented on source/index.html
> +      <div class="container slider">
сделала

2020-12-06 11:50 UTC, olga2102 commented on source/index.html
> +      <div class="container">
тогда у меня карта туда попадет, а мне же нужно, чтоб она не была ограничена.

2020-12-06 11:51 UTC, olga2102 commented on source/index.html
> +      <div class="container">
Тогда у меня фон у списка будет ограничен же?

2020-12-06 12:00 UTC, olga2102 commented on source/sass/blocks/index/advantages-item.scss
> +      transform: translate(-50%, -50%);
какая то сложная и длинная конструкция вышла, но сделала)

2020-12-06 12:04 UTC, olga2102 commented on source/sass/blocks/index/contacts.scss
> +.contacts__wrapper-tel,
Задала так, потому что .contacts__wrapper-address нужно положение менять. или ему просто модификатор задать?

2020-12-06 12:19 UTC, olga2102 commented on source/sass/blocks/index/reviews.scss
> +.reviews__next {
сложно такие длинные простыни писать без ошибок))

2020-12-06 12:21 UTC, olga2102 commented on source/sass/blocks/index/tariffs-data.scss
> +.tariffs-data-header {
Да, неправильно что то?

2020-12-06 12:44 UTC, olga2102 commented on source/sass/blocks/index/tariffs.scss
> +      line-height: 30px;
Это было ужасно. я сломала голову прежде чем это сделать нормально. если ты это не примешь, мне придется тебя убить))

2020-12-06 15:47 UTC, Shramkoweb commented on source/index.html
> +      <div class="container">
ДА. Но в статье, что я кидал был вариант решения. Ты смотрела на него?

2020-12-06 15:48 UTC, Shramkoweb commented on source/sass/blocks/index/contacts.scss
> +.contacts__wrapper-tel,
Да просто модификатор

2020-12-06 15:49 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs-data.scss
> +.tariffs-data-header {
У тебя файл `tariffs-data` а тут блок `tariffs-data-header` - это уже другой файл

2020-12-06 15:52 UTC, Shramkoweb requested changes

2020-12-06 15:52 UTC, Shramkoweb commented on source/sass/blocks/index/contacts.scss
> +.contacts__wrapper-tel,
Просто модификатор

2020-12-06 15:52 UTC, Shramkoweb commented on source/sass/blocks/index/reviews.scss
> +  }
А где простыня? Вроде как короче стало и понятно?

2020-12-06 16:35 UTC, olga2102 commented on source/sass/blocks/index/reviews.scss
> +  }
Сложно разобраться, где поставить закрывающую скобку))

2020-12-07 13:47 UTC, merged