ПП для формы мобилки и планшета
htmlacademy-adaptive/1481739-pink-21 pull request #12
Opened 2020-12-08 20:23 UTC by olga2102

2020-12-10 21:30 UTC, Shramkoweb requested changes

2020-12-10 21:30 UTC, Shramkoweb commented on source/form.html
> +          <!-- <p class="entry__text-request">Пожалуйста, заполните форму ниже:</p> -->
А что тут произошло?

2020-12-10 21:30 UTC, Shramkoweb commented on source/sass/blocks/form/entry.scss
> +    margin-top: 90px;
Можно убрать, у тебя `margin-top: 90px` уже будет с планшета

2020-12-10 21:30 UTC, Shramkoweb commented on source/sass/blocks/form/form-selection.scss
> +  height: 39px;
Вот это же уже есть от предидущего селектора. Зачем опять дублировать?

2020-12-10 21:30 UTC, Shramkoweb commented on source/sass/blocks/form/form-selection.scss
> +  background-repeat: no-repeat;
Это тоже

2020-12-10 21:30 UTC, Shramkoweb commented on source/sass/blocks/form/form-selection.scss
> +  position: absolute;
Аналогично

2020-12-10 21:30 UTC, Shramkoweb commented on source/sass/blocks/form/form-selection.scss
> +  border-radius: 50%;
Аналогично

2020-12-11 04:03 UTC, olga2102 commented on source/form.html
> +          <!-- <p class="entry__text-request">Пожалуйста, заполните форму ниже:</p> -->
Мой неравный бой с ПП)) убрала ненужное)

2020-12-11 04:13 UTC, olga2102 commented on source/sass/blocks/form/form-selection.scss
> +  position: absolute;
Так это ж у меня before и after, если я уберу это, все исчезнет

2020-12-11 15:13 UTC, Shramkoweb approved these changes

2020-12-11 15:13 UTC, merged