Добавила флекс в карточки каталога
htmlacademy-adaptive/1481739-pink-21 pull request #14
Opened 2020-12-13 17:42 UTC by olga2102

2020-12-15 18:52 UTC, Shramkoweb requested changes

2020-12-15 18:52 UTC, Shramkoweb commented on source/img/grey-background-desktop.svg
> +<svg width="1200" height="715" viewBox="0 0 1200 715" fill="none" xmlns="http://www.w3.org/2000/svg">
Я думаю можно попроюбовать єто сделать через css и не грузить картинки

2020-12-15 18:52 UTC, Shramkoweb commented on source/img/logotype-white-desktop.svg
> +<svg width="147" height="40" viewBox="0 0 147 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Это все один логотип у кторого меняется цвет заливки, fill https://css-tricks.com/change-color-of-svg-on-hover/

2020-12-15 18:52 UTC, Shramkoweb commented on source/img/triangle-white-footer.svg
> +<svg width="320" height="123" viewBox="0 0 320 123" fill="none" xmlns="http://www.w3.org/2000/svg">
Сделать на CSS

2020-12-15 18:52 UTC, Shramkoweb commented on source/index.html
> +            <source media="(min-width: 960px)" srcset="img/logotype-white-desktop.svg">
На разных версиях (мобильной, планшетной, десктопной) сделайте контентные изображения адаптивными. Они должны кадрироваться и реагировать на плотность пикселей. Обязательно кадрируйте изображения из критерия Б20.

Из-задания. Где тут плотность? Вроде как не вижу: только адаптивность

2020-12-15 18:52 UTC, Shramkoweb commented on source/sass/blocks/index/advantages.scss
> +  // background-position-y: -38px;
???

2020-12-15 18:52 UTC, Shramkoweb commented on source/sass/blocks/index/advantages.scss
> +  overflow: hidden;
???

2020-12-15 18:52 UTC, Shramkoweb commented on source/sass/blocks/index/tariffs.scss
> +      clip-path: polygon(100% 0%, 100% 100%, 0% 100%, 0% 19%);
Вот что-то похожее и сделать вместо фонов сереньких, что ты грузишь

2020-12-16 21:03 UTC, olga2102 commented on source/img/logotype-white-desktop.svg
> +<svg width="147" height="40" viewBox="0 0 147 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Давай я сделаю это в домашке по свг. я мельком просмотрела, как это делается, но хочу поподробнее почитать, чтобы нормльно понять, когда буду ту домашку делать.

2020-12-16 21:04 UTC, olga2102 commented on source/index.html
> +            <source media="(min-width: 960px)" srcset="img/logotype-white-desktop.svg">
С этим мы с тобой разобрались)

2020-12-16 21:04 UTC, olga2102 commented on source/sass/blocks/index/advantages.scss
> +  // background-position-y: -38px;
переделала

2020-12-16 21:04 UTC, olga2102 commented on source/sass/blocks/index/tariffs.scss
> +      clip-path: polygon(100% 0%, 100% 100%, 0% 100%, 0% 19%);
сделала

2020-12-16 21:06 UTC, olga2102 commented on source/sass/blocks/index/advantages.scss
> +  overflow: hidden;
убрала

2020-12-17 19:19 UTC, Shramkoweb approved these changes

2020-12-17 19:19 UTC, Shramkoweb commented on source/sass/blocks/all-pages/page-header.scss
> +      background-size: cover;
background-size: cover;
 будет с планшета уже - можно убрать

2020-12-17 19:19 UTC, merged