Стайлгайд формы и оформление модалок
htmlacademy-adaptive/1481739-pink-21 pull request #15
Opened 2020-12-17 20:19 UTC by olga2102

2020-12-18 20:29 UTC, Shramkoweb requested changes

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +                <input class="form-fieldset__input" type="mail" id="mail" name="mail" value="Введите почту *">
type="email"

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +                <input class="form-fieldset__input" type="mail" id="mail" name="mail" value="Введите почту *">
name & id

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +    <section class="form-popup form-popup-reject modal">
Может reject - это модификатор?

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +      <div class="form-popup__button-container form-popup__button-container--margin">
margin ??

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +    <section class="form-popup form-popup-accept modal">
accept - модфикатор?

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +      <div class="form-popup__button-container form-popup__button-container--background">
background - что за странные модификаторы

2020-12-18 20:29 UTC, Shramkoweb commented on source/form.html
> +      <div class="form-popup__button-container form-popup__button-container--background">
??

2020-12-18 20:29 UTC, Shramkoweb commented on source/sass/blocks/index/contacts.scss
> +.contacts__iframe-style {
iframe-style - может просто iframe?

2020-12-18 20:29 UTC, Shramkoweb commented on source/sass/blocks/index/contacts.scss
> +.contacts__iframe-style {
`.contacts__iframe`

2020-12-19 13:37 UTC, olga2102 commented on source/form.html
> +      <div class="form-popup__button-container form-popup__button-container--margin">
position пойдет?)

2020-12-19 17:39 UTC, Shramkoweb commented on source/form.html
> +      <div class="form-popup__button-container form-popup__button-container--margin">
нет

2020-12-22 18:36 UTC, Shramkoweb approved these changes

2020-12-22 18:36 UTC, merged