Разметка главной страницы
htmlacademy-adaptive/1481739-pink-21 pull request #2
Opened 2020-11-13 21:09 UTC by olga2102

2020-11-13 21:11 UTC, olga2102 commented on source/index.html
> +        <article class="research research--field">
блок появляется в десктопной и планшетной версии - это модификатор?

2020-11-14 10:29 UTC, Shramkoweb requested changes

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a href="">
Я так понял, ты на будущее классы не добавляешь? .main-nav__link например? 
Только когда он понадобится уже тебе, верно?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a href="">
Почитай тз - возможно они будут просить тут вставить ссылку на курс. Если нет, то можно уже сейчас вставить ссылку на саму академию)

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +        <a class="downloads__link" href="#">
У тебя заглушки то href="#" то другие href="" - нужно какой-то один вариант)

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a class="" href="#" aria-label="Логотип Android">
class="" ?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a class="" href="#" aria-label="Логотип Microsoft">
class=""

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <h3 class="advantages__title">Меняет мир вокруг</h3>
Это не заголовок advantages - всего блока advantages. Это заголовок конкретного advantage. Я бы для каждой  **li** создал новый блок.  И у него уже был бы свой личный элемент заголовок.

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <p class="advantages__description">Сделайте снимок и украсьте его смайликом или текстовой подписью, чтобы
Аналогично, это описание каждого конкретного преимущества, а не всех премимуществ

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +        <article class="research research--field">
Нет, это просто блок. Который скрытый на мобилке. Модификатор не нужен, это пооведение блока поумолчанию

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a class="research__link">Узнать больше об исследовании</a>
Пропал href?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +        <article class="research research--field">
А чего это **article**?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                <cite class="reviews__author-name">Николай Петров</cite>
Опять же - тут удобнее для каждого отзыва создать новый блок. И внутри него все делать.
reviews__author-name - это не имя автора всех цитат. Это имя автора конкретно цитаты

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                <p class="reviews__author-info reviews__author-info--no-info">25 лет, водитель трамвая</p>
Аналогично выше

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                <p class="reviews__author-info reviews__author-info--no-info">25 лет, водитель трамвая</p>
А что за модификатор такой? reviews__author-info--no-info

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                  фотографии!»</p>
</p> лучше перенести на новую строку, дял многострочных текстов, а то такое чу-ство, что забыла закрыть тег

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                <button class="slider__toggle" type="button"></button>
Есть критерий. Про необходимое текстовое описание, всех интерактивных элеметов. У тебя тут описания нет

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +          <h2 class="reviews__title">Тарифы</h2>
reviews__title внутри тарифов?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <table class="tariffs__list">
Это же таблица, а не список - почему тут tariffs__list?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +              </tr>
Аналогично
`tr` - tariffs__row
`td` - tariffs__data
и так далее, по тому как именуются эти тэги на английском

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +                  <b class="tariffs__name">Анлим</b>
Не ошибка, но просто для информации.
Завтра прийдет дизайнер и скажет, что тут убираем жирный и возможно тебе помимо css прийдеться еще лезть в разметку - так как тут `b`

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +              <button class="slider__toggle" type="button"></button>
slider__toggle - это элемент блока slider. А тут slider нет, это ошибка.

https://en.bem.info/forum/43/ точнее бем разрешает это формально, но на проверке могут завалить

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <p class="contacts__offer">Остались вопросы?<br>
offer - я бы назвал лучше что-то вроде contacts__call
так как тут никакого оффера нет, как по мне

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <p class="tel">Звоните:<a class="contacts__phone" href="tel:+78125556666">+7 (812) 555-66-66</a></p>
tel прям отдельный блок?

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <p class="tel">Пишите:<a class="contacts__mail" href="#">mail@htmlacademy.ru</a></p>
tel - а внутри почта. Меня это путает

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <p class="tel">Приезжайте в гости:<a class="contacts__address" href="#">ул. Большая
tel - а внутри адресс =)

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +            <a class="social__link social__link--instagram" href="https://vk.com/htmlacademy"
instagram ??  а ссылка href="https://vk.com/htmlacademy"

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +              aria-label="Мы в Фейсбуке"></a>
Мы в Фейсбуке я так понимаю. Мы для пользователя - это сайт пинк, а тут почта академии.
Что-то не так

2020-11-14 10:29 UTC, Shramkoweb commented on source/index.html
> +
??

2020-11-14 16:06 UTC, Shramkoweb requested changes

2020-11-14 16:06 UTC, Shramkoweb commented on source/index.html
> +        <button class="main-nav__toggle" type="button" aria-label="Меню"></button>
Я бы назвал - переключение меню, но это на твое усмотрение)

2020-11-14 16:06 UTC, Shramkoweb commented on source/index.html
> +            <a class="main-nav__link" href="https://htmlacademy.ru/intensive/adaptive">
А почему класс только на ней?

2020-11-14 16:06 UTC, Shramkoweb commented on source/index.html
> +        <p class="advantages__intro">Нам есть, что вам<br>
И тот и тот интро? Тогда мне кажется это какой-то text?

2020-11-14 16:06 UTC, Shramkoweb commented on source/index.html
> +        <article class="research research__field">
Так это блок или элемент? Так нельзя

2020-11-14 16:06 UTC, Shramkoweb commented on source/index.html
> +            <p class="mail">Пишите:<a class="contacts__mail" href="#">mail@htmlacademy.ru</a></p>
Тут нужно прям везде отдельные блоки?

2020-11-15 12:05 UTC, Shramkoweb approved these changes

2020-11-15 12:05 UTC, merged