Стили главной страницы
htmlacademy-adaptive/1481739-pink-21 pull request #5
Opened 2020-11-19 18:38 UTC by olga2102

2020-11-19 18:55 UTC, Shramkoweb requested changes

2020-11-19 18:55 UTC, Shramkoweb commented on source/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
Стили у нас будут локальные для шрифтов. Это убираем

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/advantages.scss
> +  &__wrapper {
https://up.htmlacademy.ru/adaptive/21/criteries#d11

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/advantages.scss
> +
Лишний отступ

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/advantages.scss
> +.advantages-item {
Это уже другой бем блок - значит новый файлик создавать надо

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/advantages.scss
> +
Лишний отступ

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/body.scss
> +.page__body {
Это неверный класс для данного файла - или наоборот имя неверно

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/contacts.scss
> +.contacts-feedback {
Это друго блок - файл

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/main-nav.scss
> +    list-style: none;
Сделай миксин для сброса стилей списка

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/page-footer.scss
> +.page-footer{
Перед кавычкой пробел

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/page-footer.scss
> +
??

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/page-header.scss
> +    background-image: url(../img/bg.jpg);
Внутри url кавычки для пути

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/reviews.scss
> +.reviews-item {
Доругой блок

2020-11-19 18:55 UTC, Shramkoweb commented on source/sass/social.scss
> +
убрать

2020-11-19 20:05 UTC, olga2102 commented on source/sass/main-nav.scss
> +    list-style: none;
я пока понятия не имею, как их делать, чуть позже почитаю, сделаю

2020-11-19 20:06 UTC, olga2102 commented on source/sass/advantages.scss
> +  &__wrapper {
а так было удобно

2020-11-20 18:16 UTC, Shramkoweb approved these changes

2020-11-20 18:16 UTC, Shramkoweb commented on source/sass/tariffs-data.scss
> +.tariffs-data--ground {
Модификаторы можно через `&` и нужно =)

2020-11-20 18:16 UTC, merged