Стили формы
htmlacademy-adaptive/1481739-pink-21 pull request #6
Opened 2020-11-20 20:40 UTC by olga2102

2020-11-20 20:42 UTC, olga2102 commented
Посмотри плиз кнопки слайдера на главной.

2020-11-20 22:12 UTC, Shramkoweb requested changes

2020-11-20 22:12 UTC, Shramkoweb commented on source/form.html
> +  <header class="page-header page-header--inner-bg">
bg - не экономь буквы =)

2020-11-20 22:12 UTC, Shramkoweb commented on source/form.html
> +            <h2 class="form-description__subtitle">Опишите свои эмоции</h2>
Почему так ?

2020-11-20 22:12 UTC, Shramkoweb commented on source/form.html
> +            <p class="form__legend"><span class="form__legend--star">*</span> — обязательные поля</p>
Это же не legend а параграф?

2020-11-20 22:12 UTC, Shramkoweb commented on source/form.html
> +            <p class="form__legend"><span class="form__legend--star">*</span> — обязательные поля</p>
span - это уже другой елемент, а не модификатор

2020-11-20 22:12 UTC, Shramkoweb commented on source/sass/form-selection.scss
> +  margin: 0;
У нас же есмть миксин?

2020-11-20 22:12 UTC, Shramkoweb commented on source/sass/form.scss
> +  background-color: rgb(42, 171, 109);
В переменную цвет?

2020-11-20 22:12 UTC, Shramkoweb commented on source/sass/tariffs-data.scss
> +  }
Я бы вынес это в начало стилей. Так как это стили общие для блока

2020-11-21 07:55 UTC, olga2102 commented on source/sass/form-selection.scss
> +  margin: 0;
Сделала)

2020-11-21 08:09 UTC, olga2102 commented on source/form.html
> +            <h2 class="form-description__subtitle">Опишите свои эмоции</h2>
Мне нечего тебе ответить в свое оправдание))) возможно что-то не получалось) видимо голова уже не работала)

2020-11-21 09:13 UTC, Shramkoweb requested changes

2020-11-21 09:13 UTC, Shramkoweb commented on source/sass/base.scss
> +html::before,
```
*,
*::before,
*::after {
  box-sizing: inherit;
}
```

2020-11-21 09:13 UTC, Shramkoweb commented on source/sass/tariffs-data.scss
> +  &--ground {
Не помню пропустит ли линтер. Но тут желательно пустую строку перед  `&--ground`

2020-11-21 09:13 UTC, Shramkoweb commented on source/sass/variables.scss
> +}
В файлик миксин

2020-11-21 09:23 UTC, olga2102 commented on source/sass/tariffs-data.scss
> +  &--ground {
ему наоборот не нравится, ошибку выдает

2020-11-21 09:27 UTC, Shramkoweb approved these changes

2020-11-21 09:27 UTC, Shramkoweb commented on source/sass/mixin.scss
> +@mixin reset() {
list-reset

2020-11-21 09:27 UTC, Shramkoweb commented on source/sass/mixin.scss
> +@mixin button() {
button-reset

2020-11-21 09:28 UTC, merged